---
modules-search: [ local ]

instances:
- id:       default
  module:   welcome
  config:   welcome.conf
- id:       default
  module:   keyboard
  config:   keyboard.conf
- id:       default
  module:   partition
  config:   partition.conf
- id:       default
  module:   mount
  config:   mount.conf
- id:       default
  module:   unpackfs
  config:   unpackfs.conf
- id:       default
  module:   fstab
  config:   fstab.conf
- id:       finalize
  module:   shellprocess
  config:   shellprocess-finalize.conf
- id:       default
  module:   users
  config:   users.conf
- id:       default
  module:   displaymanager
  config:   displaymanager.conf
- id:       default
  module:   umount
  config:   umount.conf
- id:       default
  module:   finished
  config:   finished.conf

sequence:
- show:
  - welcome
  - keyboard
  - partition
  - users
- exec:
  - partition
  - mount
  - unpackfs
  - fstab
  - users
  - displaymanager
  - shellprocess@finalize
  - umount
- show:
  - finished

branding: yerinde

prompt-install: true

dont-chroot: false

oem-setup: false

disable-cancel: false

disable-cancel-during-exec: true

hide-back-and-next-during-exec: false

quit-at-end: false
