---
initialSwapChoice: none
defaultFileSystemType: ext4
drawNestedPartitions: false
alwaysShowPartitionButtons: false
allowManualPartitioning: true
allowToggleReuse: false
# ISO'da ~16GB model+store gömülü olduğundan asgari disk kapasitesi 40GB
requiredStorage: 40
