---
showSupportUrl: false
showKnownIssuesUrl: false
showReleaseNotesUrl: false
showDonateUrl: false
requirements:
  required:
    - ram
    - storage
    - screen
  requiredStorage: 4
  requiredRam: 2
  requiredScreenWidth: 800
  requiredScreenHeight: 520
  check:
    - storage
    - ram
    - power
    - screen
  requiredFreeStorage: 5
  requiredInet: false
